- hosts: all
  gather_facts: no

  tasks:
      
    - name: Delete VM
      ec2:
        state: absent
        instance_ids: 
          - "{{ id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
