tosca_definitions_version: tosca_simple_yaml_1_3

node_types:

  sodalite.nodes.DockerVolume:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      name:
        type: string
        description: The name of the volume
        required: true
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              volume_name:          { type: string, default: { get_property: [ SELF, name ] } }
              ansible_user:         { type: string, default: { get_property: [ SELF, host, username ] } } 
            implementation:
              primary: playbooks/add_volume.yml 
          delete:
            inputs:
              volume_name:          { type: string, default: { get_property: [ SELF, name ] } }
              ansible_user:         { type: string, default: { get_property: [ SELF, host, username ] } } 
            implementation:
              primary: playbooks/remove_volume.yml   