---
- hosts: all
  gather_facts: no
  tasks:
    - name: >
        Create temporary inventory for wm, 
        since opera requires internal envvars to access the target. 
        Need more examples to access static nodes without specifying them in the inventory file
      add_host:
        name: wm
        groups: wm
        ansible_host: "{{ wm_public_address }}"
        ansible_user: "{{ wm_username }}"
        ansible_ssh_private_key_file: "{{ wm_keypath }}"
        ansible_ssh_common_args: >
          -o IdentitiesOnly=yes
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no

- hosts: wm # should be ansible module for Torque to handle jobs and their states
  gather_facts: yes
  vars:
    job_workspace_path: '{{ ( job_workspace != None ) | ternary(job_workspace, ansible_env.HOME) }}'
  tasks:
    - name: Submit the job
      shell: sbatch  {{ job_name }}.slurm
      args:
        chdir: "{{ job_workspace_path }}"
      register: job

    - name: Saving job_id
      set_fact:
        job_id: "{{ job.stdout }}"

    - name: Set attribute
      set_stats:
        data:
          job_id: "{{ job.stdout | regex_search('[0-9]+') }}"

